server:
  port: 80
  context-path: /redis
  
spring:
  redis:
    host: 192.168.44.128
    port: 6379
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 200
  redis-two:
     host: 192.168.44.128
     port: 6380
     timeout: 1000
     database: 0
     pool:
       max-active: 10
       max-idle: 8
       min-idle: 2
       max-wait: 200
